language: python
services: docker

install:
- pip install -r vvp-magics/requirements.txt

script:
- cd vvp-magics
- python -m unittest
- python setup.py sdist
- docker build -t eu.gcr.io/vvp-devel-240810/vvp-jupyter:latest .

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release-.*)$ || -n $TRAVIS_TAG