language: python
services: docker

install:
- pip install -r vvp-magics/requirements.txt

script:
- sudo ./scripts/install_gcloud.sh
- cd vvp-magics
- python -m unittest
- python setup.py sdist
- docker build -t vvp-jupyter:latest .
- openssl aes-256-cbc -K $encrypted_6d931d8515f6_key -iv $encrypted_6d931d8515f6_iv
  -in ../scripts/gcp-client-secret.json.enc -out $HOME/gcp-client-secret.json -d
- gcloud --quiet auth activate-service-account --key-file $HOME/gcp-client-secret.json
- gcloud --quiet auth configure-docker
- docker push vvp-jupyter:latest