language: python
services: docker

install:
- pip install -r vvp-magics/requirements.txt

script:
- cd vvp-magics
- python -m unittest
- python setup.py sdist

before_deploy:
- sudo ./scripts/install_gcloud.sh
- docker build -t vvp-magics/vvp-jupyter:latest .
- openssl aes-256-cbc -K $encrypted_6d931d8515f6_key -iv $encrypted_6d931d8515f6_iv
  -in scripts/gcp-client-secret.json.enc -out $HOME/gcp-client-secret.json -d
- gcloud --quiet auth activate-service-account --key-file $HOME/gcp-client-secret.json
- gcloud --quiet auth configure-docker

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branches: push_docker_image