apiVersion: v1
clusters:
- name: default
  cluster:
    server: https://127.0.0.1
contexts:
- name: default
  context:
    cluster: default
    namespace: default
current-context: default
kind: Config
preferences: {}
users: []
